Clothing Function
qbcore-framework/qb-radialmenu pull request #171
Opened 2024-01-18 15:06 UTC by Pewwww53

**Clothing as item**

2024-01-30 20:22 UTC, TKDubsta1101 requested changes
Very minor changes but the prints will annoy some people. Possibly add a config for debug prints if you want them in?

2024-01-30 20:22 UTC, TKDubsta1101 commented on locales/en.lua
> +        wrong_gender = "This clothe is not for your gender",
Spelling

2024-01-30 20:22 UTC, TKDubsta1101 commented on server/clothing.lua
> +		print(item.info.model)
Remove debug print

2024-01-30 20:22 UTC, TKDubsta1101 commented on server/clothing.lua
> +		print(item.info.model)
Remove Debug Print

2024-01-30 20:22 UTC, TKDubsta1101 commented on server/clothing.lua
> +	TriggerClientEvent('inventory:client:ItemBox', source, QBCore.Shared.Items[item], "add")
Weird indentation

2024-01-30 20:22 UTC, TKDubsta1101 commented on server/clothing.lua
> +	TriggerClientEvent('inventory:client:ItemBox', source, QBCore.Shared.Items[item], "remove")
Weird indentation

2024-01-30 20:22 UTC, TKDubsta1101 commented on server/clothing.lua
> +		TriggerClientEvent('qb-radialmenu:WearClothes', source, item, v)
Weird indentation

2024-02-26 22:04 UTC, SinisterDevelopment approved these changes

2024-05-05 15:42 UTC, closed without merging